apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "appdynamics-db-agent.fullname" }}-properties
data:
  APPDYNAMICS_AGENT_ACCOUNT_NAME: {{ .Values.properties.appdAgentAccountName }}
  APPDYNAMICS_CONTROLLER_HOST_NAME: {{ .Values.properties.appdControllerHostName }}
  APPDYNAMICS_CONTROLLER_PORT: {{ .Values.properties.appdControllerPort }}
  APPDYNAMICS_CONTROLLER_SSL_ENABLED: {{ .Values.properties.appdControllerSslEnabled }}
  APPDYNAMICS_DB_AGENT_NAME: {{ .Values.properties.appdDatabaseAgentName }}
