{{- if not .Values.properties.appdAgentAccountAccessKey.existingSecretName }}
apiVersion: v1
data:
  APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: {{  .Values.properties.appdAgentAccountAccessKey.accessKeyValue | b64enc | quote }}
kind: Secret
metadata:
  name: {{ include "appdynamics-db-agent.fullname" . }}-secret
type: Opaque
{{- end }}
