# Default values for appdynamics-db-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


# -- Configure the main properties for the agent
properties:
  # -- The 'AppDynamices Agent Account Name' used for connecting to the controller
  appdAgentAccountName: ""
  # -- The AppDynamices Agent Controller Hostname
  appdAgentAccountAccessKey:
    # -- Name of the secret to use, this will be used instead of the 'accessKeyValue' the secret key must be APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
    existingSecretName: ""
    # -- The key linked to the 'AppDynamices Agent Account Name' used to generate a secret
    accessKeyValue: ""
  appdControllerHostname: ""
  # -- The AppDynamices Agent Controller Port
  appdControllerPort: "443"
  # -- If the AppDynamices Agent Controller is using SSL
  appdControllerSslEnabled: "true"
  # -- The Database Agent Name to be used, it will be displayed in the controller for choosing the agent.
  appdDatabaseAgentName: "K8s-DB-Agent"





# -- Configure the image
image:
  repository: appdynamics/db-agent
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: 22.3.0
  pullPolicy: IfNotPresent

# -- Configure the imagePullSecrets
imagePullSecrets: []

# -- Set the number of replicas
replicas: 1

# -- If you want to override de deployment or chart name, currently: "appdynamics-db-agent"
nameOverride: ""
fullnameOverride: ""

# -- Configure the service account creation
serviceAccount:
  # -- Specifies whether a service account should be created
  create: false
  # --  Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# -- Define a podSecurityContext
podSecurityContext:
  {}
# fsGroup: 2000

# -- Define a SecurityContext for the Deployment
securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
# runAsUser: 1000

# -- Define custom resources
resources:
  {}
  # Adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
#   memory: 128Mi

# -- Configure the nodeSelector features
nodeSelector: {}

# -- Configure the pod labels
podLabels: {}

# -- Configure the pod annotations
podAnnotations: {}

# -- Configure tolerations
tolerations: []

# -- Configure affinity
affinity: {}

# -- Configure the restartPolicy
restartPolicy: Always

# -- Configure the dnsPolicy
dnsPolicy: ClusterFirst

strategy:
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%
  type: RollingUpdate


logs:
  # -- Configure the log level of the agent
  level: "info"
  persistance:
    # If you want to store logs in a persistent storage set this to tru
    #-- Configure a volume for logs persistance
    enabled: false
    # If you want to use a storage class other than the default, uncomment this
    # line and define the storage class name

    storageClass:
    # Reuse your own pre-existing PVC.
    # -- Your logs ExistingClaim if present
    existingClaim: ""

volume:
  # -- Configure a volume for logs persistance
  enabled: true
  # -- Configure a volume accessMode
  accessMode: ReadWriteOnce
  # -- Define the voluem size
  size: 1Gi
  # If you want to use a storage class other than the default, uncomment this
  # line and define the storage class name
  storageClassName: ""
  # Reuse your own pre-existing PVC.
  existingClaim: ""
